# Generated by Django 5.0.3 on 2024-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='part',
            field=models.CharField(choices=[('main', 'Main'), ('second', 'Second')], max_length=20, null=True),
        ),
    ]
