# Generated by Django 5.0.3 on 2024-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='part',
            field=models.CharField(choices=[('main', 'Main'), ('second', 'Second')], default='main', max_length=20, null=True),
        ),
    ]
