# Generated by Django 5.0.3 on 2024-05-31 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_banner_part'),
        ('products', '0030_alter_userproductview_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_cat', to='products.secondcategory'),
        ),
    ]
