# Generated by Django 5.0.3 on 2024-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_banner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='part',
            field=models.CharField(choices=[('main', 'Main'), ('second', 'Second'), ('third', 'Third')], default='main', max_length=20, null=True),
        ),
    ]
