# Generated by Django 5.0.3 on 2024-05-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_option',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_options', to='products.product'),
        ),
    ]
