# Generated by Django 5.0.3 on 2024-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
