# Generated by Django 5.0.3 on 2024-05-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
