# Generated by Django 5.0.3 on 2024-05-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profit',
        ),
    ]
