# Generated by Django 5.0.3 on 2024-05-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_seenproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(null=True, upload_to='variant_color_product/%Y/%m/%D'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Color', 'color'), ('None', 'none')], default='None', max_length=255),
        ),
    ]
