# Generated by Django 5.0.3 on 2024-05-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_color_image_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='number_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
