# Generated by Django 5.0.3 on 2024-05-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_color_number_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
