# Generated by Django 5.0.3 on 2024-05-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_color_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='image',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(null=True, upload_to='variant_color_product/%Y/%m/%D'),
        ),
    ]
