# Generated by Django 5.0.3 on 2024-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_color_image_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
