# Generated by Django 5.0.3 on 2024-05-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_variant_discount_alter_variant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
