# Generated by Django 5.0.3 on 2024-05-29 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_variant_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selle',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_product', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='firstCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.firstcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.secondcategory'),
        ),
    ]
