# Generated by Django 5.0.3 on 2024-05-29 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_selle_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selle',
            new_name='sale',
        ),
    ]
