# Generated by Django 5.0.3 on 2024-05-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_selle_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sale',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
