# Generated by Django 5.0.3 on 2024-05-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_variant_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='products/category/%Y/%M/%d'),
        ),
    ]
