# Generated by Django 5.0.3 on 2024-05-31 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_likeproduct_variant_alter_likeproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_like', to='products.product'),
        ),
    ]
