# Generated by Django 5.0.3 on 2024-05-23 09:25

import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('from_date', django_jalali.db.models.jDateTimeField()),
                ('to_date', django_jalali.db.models.jDateTimeField()),
                ('user', models.ManyToManyField(blank=True, related_name='user_coupon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
