# Generated by Django 5.0.3 on 2024-05-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.TextField(max_length=11, null=True),
        ),
    ]
