# Generated by Django 5.0.3 on 2024-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
