# Generated by Django 5.0.3 on 2024-05-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
