# Generated by Django 5.0.3 on 2024-05-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
