# Generated by Django 5.0.3 on 2024-05-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='less',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='more',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
