# Generated by Django 5.0.3 on 2024-05-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='err',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
