# Generated by Django 5.0.3 on 2024-05-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cardnumber',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
