# Generated by Django 5.0.3 on 2024-05-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_bank_order_cardnumber_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
